fix missing prototype
In file included from i18n.c:46:
locale-categories.h: In function 'get_current_locale_settings':
syscalls.h:34:11: error: implicit declaration of function 'scm_async_tick'